Feature/proyecto base
teamcubation/byma-fondos-up-back pull request #2
Opened 2024-11-07 15:53 UTC by Tavo-94

2024-11-07 19:36 UTC, DamianMarquezMeli requested changes

2024-11-07 19:36 UTC, DamianMarquezMeli commented on src/main/java/com/byma/fondos_up_back/infrastructure/adapter/in/web/mapper/GerenteControllerMapper.java
> +    }
no está validado el si el parametro es o no null

2024-11-07 19:36 UTC, DamianMarquezMeli commented on src/main/java/com/byma/fondos_up_back/infrastructure/adapter/out/persistance/GerenteOutAdapter.java
> +    }
No se validan si los parametros de entrada son o no nullos

2024-11-07 19:36 UTC, DamianMarquezMeli commented on src/main/java/com/byma/fondos_up_back/infrastructure/adapter/in/web/dto/response/GerenteResponseDTO.java
> +    private Long idOrganizacionGerente;
los id no deberian de ser la clase wrapper

2024-11-07 19:36 UTC, DamianMarquezMeli commented on src/main/java/com/byma/fondos_up_back/application/service/GerenteService.java
> +    }
No se valida si el parametro de entrada es o no vacio

2024-11-07 19:36 UTC, DamianMarquezMeli commented on src/main/java/com/byma/fondos_up_back/application/service/GerenteService.java
> +    }
No se valida si el parametro de entrada es o no vacio

2024-11-07 19:36 UTC, DamianMarquezMeli commented on src/main/java/com/byma/fondos_up_back/application/service/GerenteService.java
> +    }
No se valida si el parametro de entrada es o no vacio

2024-11-07 19:36 UTC, DamianMarquezMeli commented on src/main/java/com/byma/fondos_up_back/application/service/GerenteService.java
> +    }
No se valida si el parametro de entrada es o no vacio

2024-11-08 13:45 UTC, DamianMarquezMeli approved these changes, later dismissed

2024-11-08 13:48 UTC, julianmarcelolopez approved these changes, later dismissed

2024-11-08 13:50 UTC, merged